import {UseAuthContext} from "./Context/AuthContext"
import Hero from "./Content/hero.png"
import imgg from "./Content/img2.png"
import NavBar from "./Components/NavBar"
import NewWaves1 from "./Content/NewWaves1.svg"
import NewWaves2 from "./Content/NewWaves2.svg"


function App() {
  const {navigate } = UseAuthContext()
  

  const handleStarted = () => {
    navigate("/signup")
  }
  return (
    <div className="">
      <NavBar/>
      <div className="h-screen lg:h-[1080px] relative flex flex-col justify-center">
        <div className="m-auto max-w-max flex flex-col-reverse lg:flex-row justify-center items-center ">
          <img src={Hero} alt="hero" className="hidden lg:block w-6/12" />
          <div className="m-auto text-center lg:text-left ">
            <p className="text-4xl lg:text-7xl font-bold">Generate Unlimited KDP Interiors For Free</p>
            <button className="mt-5 text-2xl lg:text-4xl text-white bg-main p-5 rounded-xl shadow-xl" onClick={handleStarted}>Get Started</button>
          </div>
          <img src={NewWaves1} alt="wave1" className="absolute bottom-0 w-screen  " />
        </div>
      </div>
      
      <div className="section1 relative flex flex-col justify-center bg-main">
        <div className="m-auto max-w-max flex flex-col lg:flex-row-reverse justify-center items-center ">
          <img src={imgg} alt="hero" className="hidden lg:block w-6/12" />
          <div className="m-auto text-center">
            <p className="text-4xl lg:text-7xl font-bold text-white">Boost your kdp workflow by generating complex activity book interiors in seconds</p>
            <button className="mt-5 text-2xl lg:text-4xl text-main bg-white p-5 rounded-xl shadow-xl" onClick={handleStarted}>Get Started</button>
          </div>
        </div>
      </div>
      <img src={NewWaves2} alt="wave2" className=" w-screen  " />

      <div className="section1 relative flex flex-col justify-center">
        <div className="m-auto max-w-7xl flex flex-col lg:flex-row-reverse justify-center items-center ">
          <div className="m-auto text-center">
            <p className="text-4xl lg:text-7xl  font-bold">All of the files and interiors generated by this tool are free to use for both commercial and personal purposes. No attribution is necessary</p>
            <button className="mt-5 text-2xl lg:text-4xl text-white bg-main p-5 rounded-xl shadow-xl" onClick={handleStarted}>Get Started</button>
          </div>
        </div>
      </div>
      <img src={NewWaves1} alt="wave3" className=" w-screen  " />
      <div className="section1 relative flex flex-col justify-center bg-main">
        <div className="m-auto max-w-max flex flex-col lg:flex-row-reverse justify-center items-center ">
          <div className="m-auto text-center">
            <p className="text-4xl lg:text-7xl  font-bold text-white">How Does It Work ?</p>
            <div className="m-5">
              <p className="text-3xl lg:text-5xl font-bold text-white">1.Create an account (it's free)</p>
              <p className="text-3xl lg:text-5xl text-white">2.Verify your email</p>
              <p className="text-3xl lg:text-5xl text-white">3.Login and start generating</p>
            </div>
            <button className="mt-5 text-2xl lg:text-4xl text-main bg-white p-5 rounded-xl shadow-xl" onClick={handleStarted}>Get Started</button>
          </div>
        </div>
      </div>

      
    </div>
  );
}

export default App;
